version: '3.3'

services:
  warrior:
    image: atdr.meo.ws/archiveteam/warrior-dockerfile
    container_name: warrior
    hostname: warrior
    env_file: ./.settings.env
    restart: on-failure
    volumes:
      - ./data/warrior:/data/data:Z
    ports:
      - "8001:8001"
