version: '3.3'

# podman-compose --in-pod=0 up -d
# start: podman-compose-new --no-pod up -d
services:
#  syncthing:
#    image: syncthing/syncthing:latest
#    container_name: syncthing
#    hostname: syncthing
#    restart: always
#    userns_mode: keep-id
#    env_file: ./.settings.env
#    volumes:
#      - ./data/syncthing:/var/syncthing/config
#      - /media/sloan/data/Photos/Uploads/Scott:/photos-scott:z
#      - /media/sloan/data/Photos/Uploads/Gemma:/photos-gemma:z
#    ports:
#      - 8384:8384
#      - 22000:22000/tcp
#      - 22000:22000/udp
#      - 21027:21027/udp

  jottacloud:
    image: bluet/jottacloud:latest
    container_name: jottacloud
    hostname: jottacloud
    env_file: ./.settings.env
    restart: always
    volumes:
      - /media/sloan/data/Music/:/backup/Music:ro
      - /media/sloan/data/Photos/:/backup/Photos:ro
      - /media/sloan/data/TV/:/backup/TV:ro
      - /media/sloan/data/Films/:/backup/Films:ro
      - /media/sloan/data/Software/:/backup/Software:z,ro
      - ./data/jottacloud:/data/jottad:Z

  samba:
    image: crazymax/samba:latest
    container_name: samba
    restart: always
    env_file: ./.settings.env
    network_mode: host
    volumes:
      - ./data/samba:/data:Z
      - /media/sloan/data/Software:/samba/games:z,ro
      - /media/sloan/data/Photos/Uploads:/samba/uploads:z
