x-podman:
  in_pod: false

services:
  jottacloud:
    image: bluet/jottacloud:latest
    container_name: jottacloud
    hostname: jottacloud
    env_file: ./.settings.env
    restart: always
    volumes:
      - /media/sloan/data/Music/:/backup/Music:ro
      - /media/sloan/data/Photos/:/backup/Photos:ro
      - /media/sloan/data/TV/:/backup/TV:ro
      - /media/sloan/data/Films/:/backup/Films:ro
      - /media/sloan/data/Software/:/backup/Software:z,ro
      - /media/sloan/data/Books/:/backup/Books:z,ro
      - ./data/jottacloud:/data/jottad:Z

  samba:
    image: crazymax/samba:latest
    container_name: samba
    restart: always
    env_file: ./.settings.env
    network_mode: host
    volumes:
      - ./data/samba:/data:Z
      - /media/sloan/data/Software:/samba/games:z,ro
      - /media/sloan/data/Photos/Uploads:/samba/uploads:z
