# start: podman-compose up -d
x-podman:
  in_pod: false

services:
  gotosocial-se:
    image: superseriousbusiness/gotosocial:latest
    container_name: gotosocial-se
    hostname: gotosocialse
    env_file: ./.settings-se.env
    user: 1000:1000
    userns_mode: "keep-id:uid=1000,gid=1000"
    restart: always
    volumes:
      - ./data/db-se:/gotosocial/storage:Z
    networks:
      fediverse:
        ipv4_address: 172.2.1.2

  gotosocial-ge:
    image: superseriousbusiness/gotosocial:latest
    container_name: gotosocial-ge
    hostname: gotosocialge
    env_file: ./.settings-ge.env
    user: 1000:1000
    userns_mode: "keep-id:uid=1000,gid=1000"
    restart: always
    volumes:
      - ./data/db-ge:/gotosocial/storage:Z
    networks:
      fediverse:
        ipv4_address: 172.2.1.3

  cloudflared-fediverse:
    image: cloudflare/cloudflared:latest
    container_name: cloudflared-fediverse
    hostname: cloudflaredfediverse
    command: tunnel --no-autoupdate run --token ${CF_FEDIVERSE_TOKEN}
    restart: always
    depends_on:
      - gotosocial-se
      - gotosocial-ge
    networks:
      fediverse:
        ipv4_address: 172.2.1.4

networks:
  fediverse:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.2.1.0/16
          gateway: 172.2.1.1
